# Generated by Django 4.2.11 on 2026-03-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_task_ty_265be9_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='task',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='task',
            name='input_file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='max_retries',
        ),
        migrations.RemoveField(
            model_name='task',
            name='output_data',
        ),
        migrations.RemoveField(
            model_name='task',
            name='output_file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='task',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='task',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
    ]
